### ISSUE TITLE
Doc: review document what changes spartacussample does

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront-docs#138]
See also #2766

It's meant for someone who wants to adapt their data to Sparatcus by changing components or labels.

**Comment by WeizhengSap** [comment]
PR is here: https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/pull/204

To technical writer: please polish it, and add some description to this addon (now, I leave it as ... :) )
