### ISSUE TITLE
Promote Spartacus slack mention link to top of first few intro pages

### ISSUE THREAD

**Issue by Xymmer** [SAP/cloud-commerce-spartacus-storefront-docs#342]
I'm often asked for the slack link, and looking at the docs, the pages in the 'about' section either dont' have the link or have it down lower... can you add same slack-spartacus paragraph and link to top of each page so that it's easily seen? Also to the readme's in docs and code githubs.

**Comment by gladius-mtl** [comment]
GitHub ticket in code repo for adding Slack link to readme: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5042
