### ISSUE TITLE
Document Style guidelines [dependency on css refactoring]

### ISSUE THREAD

**Issue by developpeurweb** [SAP/cloud-commerce-spartacus-storefront-docs#61]
Document style guidelines in a README file for open source public contributors.
File is already created and located here:
`/projects/storefrontstyles/README.md`
Also keep documenting the Design System so devs can learn it once released.

was SPA-1392

we need the lipstick ui / css refactoring done and then get back to this ticket

**Update**
The text in `/projects/storefrontstyles/README.md` needs updating to reflect recent changes. Further input may be required from @developpeurweb or @LTiger14 or @tobi-or-not-tobi . 
When this readme is updated, it should probably point to the wiki for in-depth information about styling.

**Comment by gladius-mtl** [comment]
Much about Spartacus styling has changed since the creation of this ticket. Closing because it's no longer needed.
